export interface Avatar {
    name: string;
    headImage: string;
    fullImage: string;
    mineshaftImage: string;
    standing: string;
    dog_petting: string;
    lost: string;
    fight: string;
}

export const AvatarEnum = {
    Steve: {
        name: 'Steve',
        headImage: 'assets/images/avatar/Steve_head.png',
        fullImage: 'assets/images/avatar/Steve.png',
        mineshaftImage: 'assets/images/Skins/STeve/steve_mineshaft.jpg',
        standing: 'assets/images/Skins/STeve/standing.jpg',
        dog_petting: 'assets/images/Skins/STeve/dog_petting.jpg',
        lost: 'assets/images/Skins/STeve/lost.jpg',
        fight: 'assets/images/Skins/STeve/fight.jpg',
    },
    Arlina: {
        name: 'Arlina',
        headImage: 'assets/images/avatar/GirlSkin1_head.png',
        fullImage: 'assets/images/avatar/GirlSkin1.png',
        mineshaftImage: 'assets/images/Skins/Arlina/alrina_mineshaft.png',
        standing: 'assets/images/Skins/Arlina/standing.jpg',
        dog_petting: 'assets/images/Skins/Arlina/dog_petting.jpg',
        lost: 'assets/images/Skins/Arlina/lost.jpg',
        fight: 'assets/images/Skins/Arlina/fight.jpg',
    },
    Alex: {
        name: 'Alex',
        headImage: 'assets/images/avatar/Alex_head.png',
        fullImage: 'assets/images/avatar/Alex.png',
        mineshaftImage: 'assets/images/Skins/Alex/alex_mineshaft.png',
        standing: 'assets/images/Skins/Alex/standing.jpg',
        dog_petting: 'assets/images/Skins/Alex/dog_petting.jpg',
        lost: 'assets/images/Skins/Alex/lost.jpg',
        fight: 'assets/images/Skins/Alex/fight.jpg',
    },
    King: {
        name: 'King',
        headImage: 'assets/images/avatar/King_head.png',
        fullImage: 'assets/images/avatar/King.png',
        mineshaftImage: 'assets/images/Skins/King/king_mineshaft.jpg',
        standing: 'assets/images/Skins/King/standing.jpg',
        dog_petting: 'assets/images/Skins/King/dog_petting.jpg',
        lost: 'assets/images/Skins/King/lost.jpg',
        fight: 'assets/images/Skins/King/fight.jpg',
    },
    Cosmic: {
        name: 'Cosmic',
        headImage: 'assets/images/avatar/Cosmic._head.png',
        fullImage: 'assets/images/avatar/Cosmic.png',
        mineshaftImage: 'assets/images/Skins/Cosmic/cosmic_mineshaft.png',
        standing: 'assets/images/Skins/Cosmic/standing.jpg',
        dog_petting: 'assets/images/Skins/Cosmic/dog_petting.jpg',
        lost: 'assets/images/Skins/Cosmic/lost.jpg',
        fight: 'assets/images/Skins/Cosmic/fight.jpg',
    },
    Sirene: {
        name: 'Sirene',
        headImage: 'assets/images/avatar/Sirene_head.png',
        fullImage: 'assets/images/avatar/Sirene.png',
        mineshaftImage: 'assets/images/Skins/Sirene/sirene_mineshaft.jpg',
        standing: 'assets/images/Skins/Sirene/standing.jpg',
        dog_petting: 'assets/images/Skins/Sirene/dog_petting.jpg',
        lost: 'assets/images/Skins/Sirene/lost.jpg',
        fight: 'assets/images/Skins/Sirene/fight.jpg',
    },
    Zombie: {
        name: 'Zombie',
        headImage: 'assets/images/avatar/zombie_head.png',
        fullImage: 'assets/images/avatar/zombie.png',
        mineshaftImage: 'assets/images/Skins/Zombie/zombie_mineshaft.jpg',
        standing: 'assets/images/Skins/Zombie/standing.jpg',
        dog_petting: 'assets/images/Skins/Zombie/dog_petting.jpg',
        lost: 'assets/images/Skins/Zombie/lost.jpg',
        fight: 'assets/images/Skins/Zombie/fight.jpg',
    },
    Mushroom: {
        name: 'Mushroom',
        headImage: 'assets/images/avatar/Muffin_head.png',
        fullImage: 'assets/images/avatar/Muffin.png',
        mineshaftImage: 'assets/images/Skins/Mushroom/mushroom_mineshaft.jpg',
        standing: 'assets/images/Skins/Mushroom/standing.jpg',
        dog_petting: 'assets/images/Skins/Mushroom/dog_petting.jpg',
        lost: 'assets/images/Skins/Mushroom/lost.jpg',
        fight: 'assets/images/Skins/Mushroom/fight.jpg',
    },
    Piglin: {
        name: 'Piglin',
        headImage: 'assets/images/avatar/Piglin_head.png',
        fullImage: 'assets/images/avatar/Piglin.png',
        mineshaftImage: 'assets/images/Skins/Pigman/pigman_mineshaft.jpg',
        standing: 'assets/images/Skins/Pigman/standing.jpg',
        dog_petting: 'assets/images/Skins/Pigman/dog_petting.jpg',
        lost: 'assets/images/Skins/Pigman/lost.jpg',
        fight: 'assets/images/Skins/Pigman/fight.jpg',
    },
    Strawberry: {
        name: 'Strawberry',
        headImage: 'assets/images/avatar/StrawberryShortcake_head.png',
        fullImage: 'assets/images/avatar/StrawberryShortcake.png',
        mineshaftImage: 'assets/images/Skins/StrawberryShortcake/strawberry_Shortcake_mineshaft.jpg',
        standing: 'assets/images/Skins/StrawberryShortcake/standing.jpg',
        dog_petting: 'assets/images/Skins/StrawberryShortcake/dog_petting.jpg',
        lost: 'assets/images/Skins/StrawberryShortcake/lost.jpg',
        fight: 'assets/images/Skins/StrawberryShortcake/fight.jpg',
    },
    Knight: {
        name: 'Knight',
        headImage: 'assets/images/avatar/Knight_head.png',
        fullImage: 'assets/images/avatar/Knight.png',
        mineshaftImage: 'assets/images/Skins/Knight/knight_mineshaft.jpg',
        standing: 'assets/images/Skins/Knight/standing.jpg',
        dog_petting: 'assets/images/Skins/Knight/dog_petting.jpg',
        lost: 'assets/images/Skins/Knight/lost.jpg',
        fight: 'assets/images/Skins/Knight/fight.jpg',
    },
    Finn: {
        name: 'Finn',
        headImage: 'assets/images/avatar/finn_head.png',
        fullImage: 'assets/images/avatar/finn.png',
        mineshaftImage: 'assets/images/Skins/Finn/finn_mineshaft.jpg',
        standing: 'assets/images/Skins/Finn/standing.jpg',
        dog_petting: 'assets/images/Skins/Finn/dog_petting.jpg',
        lost: 'assets/images/Skins/Finn/lost.jpg',
        fight: 'assets/images/Skins/Finn/fight.jpg',
    },
} as const;
